#!/usr/bin/env node
// Reads .env (or the file passed via --env <path>) and the Google service
// account JSON, and writes bin/baked.js. That file is picked up by pkg and
// embedded into the .exe so the shipped binary contains everything needed
// to run -- no config.json or service-account.json alongside required.
//
// The generated file is gitignored; regenerate it whenever creds change.

const fs = require("fs");
const path = require("path");

function parseArgs(argv) {
  const out = {};
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--env" || a === "-e") out.envPath = argv[++i];
    else if (a === "--key" || a === "-k") out.keyPath = argv[++i];
    else if (a === "--out" || a === "-o") out.outPath = argv[++i];
  }
  return out;
}

function loadDotenv(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`env file not found: ${filePath}`);
  }
  const text = fs.readFileSync(filePath, "utf8");
  const env = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    env[key] = val;
  }
  return env;
}

function requireField(env, name) {
  const v = env[name];
  if (!v) throw new Error(`missing required field in env: ${name}`);
  return v;
}

function main() {
  const args = parseArgs(process.argv);
  const root = path.resolve(__dirname, "..");
  const envPath = path.resolve(args.envPath || path.join(root, ".env"));
  const keyPath = path.resolve(
    args.keyPath ||
      process.env.GOOGLE_SERVICE_ACCOUNT_KEY_PATH ||
      path.join(root, "secrets", "service-account.json")
  );
  const outPath = path.resolve(args.outPath || path.join(root, "bin", "baked.js"));

  console.log(`Reading env from:            ${envPath}`);
  console.log(`Reading service account key: ${keyPath}`);
  console.log(`Writing baked module to:     ${outPath}`);

  const env = loadDotenv(envPath);

  // Required fields for the app to actually work
  requireField(env, "UNICOMMERCE_USERNAME");
  requireField(env, "UNICOMMERCE_API_KEY");
  requireField(env, "GOOGLE_SHEET_ID");

  if (!fs.existsSync(keyPath)) {
    throw new Error(`service account JSON not found: ${keyPath}`);
  }
  const rawKey = fs.readFileSync(keyPath, "utf8");
  let parsedKey;
  try {
    parsedKey = JSON.parse(rawKey);
  } catch (err) {
    throw new Error(`service account JSON is not valid JSON: ${err.message}`);
  }

  const baked = {
    unicommerceTenantUrl: env.UNICOMMERCE_TENANT_URL || "https://baidyanatheast.unicommerce.com",
    unicommerceUsername: env.UNICOMMERCE_USERNAME,
    unicommerceApiKey: env.UNICOMMERCE_API_KEY,
    googleSheetId: env.GOOGLE_SHEET_ID,
    googleServiceAccountJson: parsedKey,
    drrWindowDays: env.DRR_WINDOW_DAYS ? Number(env.DRR_WINDOW_DAYS) : undefined,
    reorderThresholdDays: env.REORDER_THRESHOLD_DAYS ? Number(env.REORDER_THRESHOLD_DAYS) : undefined,
    leadTimeDays: env.LEAD_TIME_DAYS ? Number(env.LEAD_TIME_DAYS) : undefined,
    safetyStockDays: env.SAFETY_STOCK_DAYS ? Number(env.SAFETY_STOCK_DAYS) : undefined,
    getSaleOrderConcurrency: env.GET_SALE_ORDER_CONCURRENCY ? Number(env.GET_SALE_ORDER_CONCURRENCY) : undefined,
  };

  const banner =
    "// AUTO-GENERATED by scripts/bake.js. Do NOT commit -- contains secrets.\n" +
    "// Regenerate with: npm run bake\n";
  const body = `module.exports = ${JSON.stringify(baked, null, 2)};\n`;
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, banner + body, { mode: 0o600 });

  console.log(`\nOK. Baked ${Object.keys(baked).filter((k) => baked[k] !== undefined).length} fields into ${outPath}`);
  console.log(`Service account email: ${parsedKey.client_email || "(missing)"}`);
  console.log(`Now run: npm run build:win`);
}

try {
  main();
} catch (err) {
  console.error(`bake failed: ${err.message}`);
  process.exit(1);
}
